require '/space/cassj/catpaws/lib/catpaws/ec2'
require 'find'
require 'fileutils'
require 'aws/s3'

###################################################################
# liftOver the ELAND mm8-aligned data and run Macs on it 
#
# CMN038 = NS5 Input
# CMN039 = NS5 H3K4Ac ChIP
#
# CME088 = C18 (ESC K/O REST) Input
# CME089 = C18 (ESC K/O REST) H3K9Ac ChIP
#
# CME090 = D4 (WT ESC) Input
# CME091 = D4 (WT ESC) H3k9Ac ChIP
#


######
# config for catpaws

# data is on us-east, so we'll run the instances there too.

set :aws_access_key,  ENV['AMAZON_ACCESS_KEY']
set :aws_secret_access_key , ENV['AMAZON_SECRET_ACCESS_KEY']
set :ec2_url, 'us-east-1.ec2.amazonaws.com' #us-east, cos that's where the data is. annoyingly.
set :ssh_options, { :user => "ubuntu", :keys => ['/home/cassj/ec2/cassj_useast.pem'] }
set :key, 'cassj_useast'
set :ami, 'ami-2d4aa444' #32bit vanilla ubuntu Lucid
set :instance_type, 'm1.small'
set :working_dir, '/mnt/chipseq'
set :script_dir, working_dir+'/scripts'
role(:master, 'localhost')
set :nhosts, 1


#set :group_name, 'rest109'
#set :input   , 's3://sorted.buckley.gis100710.CMN036/sorted.txt'
#set :chip    , 's3://sorted.buckley.gis100710.CMN037/sorted.txt'

#set :group_name, 'ns5k4'
#set :input   , 's3://sorted.buckley.gis100710.CMN038/sorted.txt'
#set :chip    , 's3://sorted.buckley.gis100710.CMN039/sorted.txt'


#set :group_name, 'c18k9ac'
#set :input   , 's3://sorted.buckley.gis100710.CME088/sorted.txt'
#set :chip    , 's3://sorted.buckley.gis100710.CME089/sorted.txt'


set :group_name, 'd4k9ac'
set :input   , 's3://sorted.buckley.gis100710.CME090/sorted.txt'
set :chip    , 's3://sorted.buckley.gis100710.CME091/sorted.txt'


desc "install s3 client"
task :install_s3, :roles => group_name do
  sudo 'apt-get update'
  sudo 'apt-get install -y s3cmd'
  upload('/space/cassj/GIS_15_07_10/ChIPseq/scripts/s3cfg', '/home/ubuntu/.s3cfg')
end
before 'install_s3', 'EC2:start'

task :data_dir, :roles => group_name do
  sudo "mkdir -p /mnt/chipseq"
  sudo "chown -R ubuntu /mnt/chipseq"
end
before "data_dir", "install_s3"

task :fetch_files, :roles => group_name do 
  run "cd /mnt/chipseq && s3cmd get #{input} input.txt"
  run "cd /mnt/chipseq && s3cmd get #{chip} chip.txt"
end
before "fetch_files", "data_dir" 

task :make_bed, :roles => group_name do
  run "cd /mnt/chipseq && wget http://github.com/cassj/my_bioinfo_scripts/raw/master/ngs/illumina/sorted2bed.pl"
  run "cd /mnt/chipseq && chmod +x sorted2bed.pl"
  run "cd /mnt/chipseq && /mnt/chipseq/sorted2bed.pl input.txt > input.bed"
  run "cd /mnt/chipseq && /mnt/chipseq/sorted2bed.pl chip.txt > chip.bed"
end 
before 'make_bed', 'fetch_files'


task :install_macs, :roles => group_name do
  sudo "apt-get install -y python"
  run "cd /mnt/chipseq && wget --http-user macs --http-passwd chipseq http://liulab.dfci.harvard.edu/MACS/src/MACS-1.4.0alpha2.tar.gz"
  run "cd /mnt/chipseq && tar -xvzf MACS-1.4.0alpha2.tar.gz"
  run "cd /mnt/chipseq/MACS-1.4.0alpha2 && sudo python setup.py install"
  sudo "ln -s /usr/local/bin/macs14 /usr/local/bin/macs"
end
before "install_macs", 'make_bed'

task :run_macs, :roles => group_name do
  sudo "apt-get -y install r-base r-base-dev"
  run "cd /mnt/chipseq && rm -Rf run*"
  run "cd /mnt/chipseq && rm -Rf multi_macs.pl"
  run "cd /mnt/chipseq && wget http://github.com/cassj/my_bioinfo_scripts/raw/master/ngs/macs/multi_macs.pl"
  run "chmod +x /mnt/chipseq/multi_macs.pl"
  run "cd /mnt/chipseq && /mnt/chipseq/multi_macs.pl chip.bed input.bed "
end
before 'run_macs', 'install_macs'

#pack up the runs and s3 them
task :gzip_macs, :roles => group_name do
  run "cd /mnt/chipseq &&  tar -cvzf macs.tgz run*"
  run "s3cmd mb s3://#{group_name}_macs"
  run "cd /mnt/chipseq && s3cmd put macs.tgz  s3://#{group_name}_macs"
end
before 'gzip_macs','run_macs' 
after 'gzip_macs','EC2:stop'









